### ISSUE TITLE
Error occured on Private API when using pip install

### ISSUE THREAD

**Issue by namuyan** [bitbankinc/python-bitbankcc#2]
Hello, I use python3.6 on windows10 64bit.
I have error when using pip installed python-bitbankcc (0.0.1) .
I solved error by installing from github directly `pip install git+https://github.com/bitbankinc/python-bitbankcc.git` (0.0.3) .

Please update version on pip. :)

**Comment by junderw** [comment]
Thanks for the report.

Looking deeper, PyPi has apparently made some large changes, so I will go ahead and recommend using github with pip to install.

To remove confusion I have deleted the package on pypi.
Old link (now broken): https://pypi.python.org/pypi/python_bitbankcc
